POST http://localhost:5000/api/goods
Content-Type: application/json

{
  "uEmail" : "chemra@gmail.com",
    "name": "TOURING BIKES",
  "image": "https://i.ibb.co/GdLK1Cv/touring-bike.jpg",
  "desc": "Touring bikes are like road bikes that have been specially adapted to carry loads over longer distances. They’re designed for long days out where stability, practicality and rider comfort are as important as performance, and they take pannier racks, mudguards and slightly wider tyres.",
  "price": 1500,
  "quantity": 2055,
  "sold": 0,
  "supplier": "City Bike DEU"
}

###
POST http://localhost:5000/api/blogs
Content-Type: application/json

{
  "title": "Difference Between JavaScript and Node.Js",
  "desc" : "JavaScript is one of the most popular scripting languages that are supported by most browser and mostly used in client side. On the other hand Node Js is a JavaScript interpreter with some valuable libraries that are used to run JavaScript on the server side. NodeJs is not only written in JavaScript but also it uses C/C++.",
  "author" : "Mr Unga Bunga"
}