POST http://localhost:5000/api/goods
Content-Type: application/json

{
  "uEmail" : "chemra@gmail.com",
    "name": "TOURING BIKES",
  "image": "https://i.ibb.co/GdLK1Cv/touring-bike.jpg",
  "desc": "Touring bikes are like road bikes that have been specially adapted to carry loads over longer distances. They’re designed for long days out where stability, practicality and rider comfort are as important as performance, and they take pannier racks, mudguards and slightly wider tyres.",
  "price": 1500,
  "quantity": 2055,
  "sold": 0,
  "supplier": "City Bike DEU"
}

###
POST http://localhost:5000/api/blogs
Content-Type: application/json

{
  "title": "When should one use nodejs and when should one use mongodb?",
  "image": "https://i.ibb.co/6Y0JHfK/jsvsnode.png",
  "desc" : "NodeJs is great for making real time applications such as online games or chatrooms anything where what one user does with the application needs to be seen by other users immediately, without a page refresh. Besides, we can use the same language JavaScript for the server and client both side even can share same codesif needed. From my personal perspective I would like to use MongoDB for it's lower complexity. I prefer document databases because of how they organize data as well as they support query languages. MongoDB is usually categorized under NoSQL Database. NoSQL database means usually the data model will be organized in a document other than tabular form.",
  "author" : "Zillur Rahman"
}